<?xml version="1.0" encoding="utf-8"?><Database Name="DataSource" Class="ExpenseDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=mssql4.gear.host;Persist Security Info=True;User ID=expensemasterdb" SettingsObjectName="PersonalExpenseApp.Properties.Settings" SettingsPropertyName="DataSourceConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Income" Member="Incomes">
    <Type Name="Income">
      <Column Name="No" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Amount" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Travel" Member="Travels">
    <Type Name="Travel">
      <Column Name="No" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Amount" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Leisure" Member="Leisures">
    <Type Name="Leisure">
      <Column Name="No" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Amount" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Misc" Member="Miscs">
    <Type Name="Misc">
      <Column Name="No" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Amount" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Summary" Member="Summaries">
    <Type Name="Summary">
      <Column Name="No" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Credit" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Debit" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Balance" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Function Name="dbo.UpdateSummary" Method="UpdateSummary">
    <Return Type="System.Int32" />
  </Function>
</Database>